### ISSUE TITLE
RFC: New Bundle (AssetOptimizerBundle)

### ISSUE THREAD

**Issue by henrikbjorn** [FriendsOfSymfony/friendsofsymfony.github.io#1]
Hey everyone.

I would like to propose to add AssetOptimizerBundle into FOS as our second bundle. The bundle is a way to optimize assets (js/css) by combining and minifying them. But we have talked about adding the notion of Processors that also will help by parsing .less files and other 3rd party stuff like .sass.

Also i would like to propose that we add dstendardi as a new member as he is the one who started the bundle and also have some interesting stuff underway as a SearchBundle where multiple backends are abstracted (ElasticSearch,Solr, etc).

Please use the +1 or -1 in comments if you are okay with this or against.

Best regards
Henrik Bjørnskov.

**Comment by lsmith77** [comment]
+1 and +1

**Comment by Herzult** [comment]
- +1 Yeah, it seems to be a good idea as it is a very common feature.
- +1 To add dstendardi

**Comment by schmittjoh** [comment]
+1/+1

**Comment by stof** [comment]
+1 and +1

**Comment by henrikbjorn** [comment]
The majority have accepted the two proposals. :) Welcome to dstendardi

**Comment by mahono** [comment]
don't know the state of this bundle, but imho this is now obsolete

**Comment by stof** [comment]
Sure, this is why the repo has not been created and the issue is closed.
