### ISSUE TITLE
JenkinsBundle to join the FOS  group?

### ISSUE THREAD

**Issue by hhamon** [FriendsOfSymfony/friendsofsymfony.github.io#11]
Hi all,

I have started to work this weekend on a very basic FOSJenkinsBundle to integrate Jenkins logs to the web debug toolbar and the profiler application. For now, the bundle is really simple as I only parse an RSS file coming from Jenkins to display in the web debug toolbar the status of the last build (succeeded or not) and the status of the last 10 builds in a panel of the profiler.

In the future, I would like to show more usefull information in the Jenkins panel like the code coverage rate, number of unit tests (passed and failed), link to the generated phpdoc, phpmd logs, pdepend logs, phpcpd logs... Basically, I just want to publish artefacts that Jenkins generates but in my profiler panel to centralize everything in my project. The goal is to avoid to open Jenkins to see these logs.

I don't know if you could be interested for this kind of bundle but I'm pretty sure it would be usefull for lots of developers and it will show how Symfony2 is able to help developers be more productive and efficient.

If you want to watch the code of the bundle, you can find the repository on my account here:

https://github.com/hhamon/FOSJenkinsBundle

The current code doesn't work pretty well as I didn't commit the DependencyInjection extension but I will do it this week.

Are you ok to make this JenkinsBundle join the FOS usergroup?

Hugo Hamon
Sensio Labs Trainings Manager.

**Comment by jmikola** [comment]
I'm not sure how many folks are using CI for their own projects (although OpenSky is) and would be able to contribute, but this sounds interesting. You certainly have a development roadmap in place, so there's lots of individual features folks could contribute to.

:+1:

**Comment by lsmith77** [comment]
We are also using CI here at Liip, though most projects are using Bamboo, but one is also using Hudson (probably soon to be Jenkins). Maybe a generic CI Bundle would make more sense? But in general I am +1 on adding this.

I can try and see if someone at Liip is interested in adding Bamboo support.

**Comment by beberlei** [comment]
I think the target audience is too specific to justify it being a FoS bundle, even if several CI servers are supported.

-1

**Comment by hhamon** [comment]
@jmikola for now, I only want to focus on Jenkins and Quality Assurance (QA) tools to monitor the quality of PHP projects. The ideal would be to display QA metrics in the profiler application.

@lsmith77 Yes it would be great if we could have a CIBundle that includes several adapter to gather logs from Jenkins, CruiseControl, Maven, Bamboo or whatever CI tool. If someone is interested to integrate a Bamboo support, we could go for a CIBundle. Otherwise, I think we can focus on a Jenkins integration first.

@beberlei indeed the audience is really specific but the FoS group is not only dedicated to ultra "generic" bundles as far as I know. Is it?

**Comment by lsmith77** [comment]
So far the criteria has been more if enough of the existing members have an interest.

**Comment by arghav** [comment]
Well I have not used Jenkins yet but I am planning to dig in, in a few weeks. So it might come in handy. So a +1 from me.

**Comment by Seldaek** [comment]
I'm just asking away here, don't take it the wrong way, but instead of parsing all the stuff and displaying it in the jenkins panel, did you consider a simple iframe to the jenkins report page? I know it sounds bad and all, but when you think of it, it'll save you lots of time, and will be much more informative and flexible than "whatever we decide to parse".

**Comment by hhamon** [comment]
Hi Jordi,

I already thought about adding an iframe to Jenkins instead of getting information and parsing reports to display what I wish. I sounds a good idea but I would prefer displaying some summary information in a sexier way with links to details. For example, I want to display the number of passed tests and failed tests and then a link to a more detailed page on Jenkins. I think it's better to only show some reports summaries and link them to more detailed Jenkins pages instead of wrapping the Jenkins dashboard into an iframe.

I also thought about gathering data from Jenkins and inserting them in an sqlite or mongodb database for generate statistics. But I'm not really convinced for now as Jenkins delivers all these statistics, I just need to find a way to retrieve them from an API or by publishing artefacts in a folder accessible from the web.

**Comment by lsmith77** [comment]
I think being able to provide the number of failed tests in the toolbar makes absolute sense, however for the rest I guess an iframe would indeed do the trick and would make supporting other CI server solutions a lot easier.

**Comment by dustinwhittle** [comment]
+1 - I think a CI bundle would be appropriate for FOS -- it is generic enough concept that a lot of projects will need.

**Comment by merk** [comment]
Ping -- With most of us using Travis-ci, does this bundle still have relevance?

**Comment by hhamon** [comment]
I have stopped to work on a Jenkins bundle as of now.
