### ISSUE TITLE
should we create a FOS mailinglist?

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#12]
Henrik poked me about creating a RestBundle mailinglist since I started asking questions on symfony-dev@. I think this is a bit over the top and John Wards suggested instead to create a FOS mailinglist which makes more sense to me.

**Comment by stof** [comment]
+1 for a FOS mailing-list

**Comment by everzet** [comment]
I think, yes!

**Comment by arghav** [comment]
@lsmith77 Why move away from symfony-dev@? Is there any particular reason?

**Comment by lsmith77** [comment]
Well because its not "strictly" about Symfony. Also for example I do not subscribe to symfony-users@.

**Comment by arghav** [comment]
Okay that explains. So a +1 for FOS mailing-list.

**Comment by hhamon** [comment]
Sounds a good idea!

**Comment by lsmith77** [comment]
OK, since there wasnt any real opposition:
http://groups.google.com/group/friendsofsymfony-dev/
