### ISSUE TITLE
Invite merk in the glorious FOS team

### ISSUE THREAD

**Issue by ornicar** [FriendsOfSymfony/friendsofsymfony.github.io#13]
@merk (https://github.com/merk) has been commiting on CommentBundle for a long time. I want him to give him write access to the repo. I'm sure he makes a great addition to the team.
Votes please :)

**Comment by avalanche123** [comment]
:+1:

**Comment by arghav** [comment]
+1

**Comment by arghav** [comment]
Gah... I should go get some coffee! Sorry for closing!

**Comment by schmittjoh** [comment]
+1

**Comment by Herzult** [comment]
:+1:

**Comment by lsmith77** [comment]
+1

**Comment by ornicar** [comment]
ok I guess it's enough. Welcome merk, by these words we dub you knight of FOS chivalry.

**Comment by merk** [comment]
Thanks guys, great to be part of the awesomeness of FOS :)
