### ISSUE TITLE
Add GoogleBundle?

### ISSUE THREAD

**Issue by dustinwhittle** [FriendsOfSymfony/friendsofsymfony.github.io#15]
Can we add https://github.com/antimattr/googlebundle to fos?

**Comment by merk** [comment]
It would be up to @tirnanog06 - It looks like he already has set up a vendor namespace to house many bundles.

I would vote that a GoogleBundle would be a nice thing to have here, but there is no point in duplicating effort.

**Comment by dustinwhittle** [comment]
Yes, I meant migrating the googlebundle to FOS namespace to consolidate efforts if tirnanog06 is up for it.

**Comment by lsmith77** [comment]
In general I personally expect to use this bundle eventually, so in general I am +1. However the big question is if @tirnanog06 sees a benefit in terms of additional support and maybe also visibility. One thing I noticed is that I didnt see a LICENSE file in the bundle.

**Comment by arghav** [comment]
Isn't OpenSky already maintaining it? 
I'm +1 on this if we don't duplicate the effort.

**Comment by stof** [comment]
Opensky has its own GoogleBundle but it has not been updated since December.
I don't know if they use antimattr/GoogleBundle now.

**Comment by merk** [comment]
No response from @tirnanog06, feel free to reopen issue if furthur discussion is warranted.
