### ISSUE TITLE
Contributor License Agreements?

### ISSUE THREAD

**Issue by dustinwhittle** [FriendsOfSymfony/friendsofsymfony.github.io#16]
Does a standard MIT license + CLA process make sense for FOS bundle contributors?

**Comment by merk** [comment]
lsmith is quite vocal against the CLA process, and I see no point for it.

i also dont see any point when the core framework is not covered by a CLA either.

**Comment by dustinwhittle** [comment]
I am not big on it either, but since the community is really just getting started I thought I would propose it. 

Any other feedback?

**Comment by lsmith77** [comment]
a CLA without indemnification provides no added legal security really, while adding a ton of legal hurdles for contributors.

**Comment by dustinwhittle** [comment]
Basically, all I was really looking for was some form of a statement that contributors commit code in good faith and that it is an original work not borrowed or otherwise bound to an incompatible license. I agree it provides little protection and adds unnecessary hurdles.

**Comment by lsmith77** [comment]
I invite everyone to open feature requests with github to optionally add a simple checkbox with some legal bla bla before submitting a PR. like having to acknowledge the license. this would help streamline the legal process but wouldnt be some crazy legal hurdle.

**Comment by arghav** [comment]
@lsmith77 Didn't you open a feature request for something similar previously?

**Comment by lsmith77** [comment]
Yes I did. Their answer was that it sounded sensible, but they will not prioritize it unless they get more requests. Furthermore they do not make feature requests public, as they want people to have to show more initiative than just a +1 comment.

**Comment by dustinwhittle** [comment]
I just sent a feature request for this issue too.
