### ISSUE TITLE
add an FAQBundle

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#19]
for now i would keep it simple, but it could slowly grow.

step one would be to just support ORM/ODM's for storage with a simple (ordered?) list of questions and answers. the list of questions is outputted at the top with links to the questions/answers at the bottom.

in terms of administration i for now only need an xml import.

i should also note that maybe this would better fit in the CMF project.

**Comment by stof** [comment]
This bundle could be a useful one but I think that the CMF project seems to be a better place for it.

**Comment by jmikola** [comment]
I agree re: CMF. This doesn't seem substantial enough to warrant a full bundle, unless it was to serve as an example application.

**Comment by lsmith77** [comment]
k .. closing
