### ISSUE TITLE
spinning off FOSRest from FOSRestBundle

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#24]
not sure quite sure yet what the scope will be, but for now I think it will cover request body decoding (json/xml ..) as well as media type negotiations (aka port mod_negotiation). not sure yet if this code will remain here either as I am looking to collaborate with people from Typo3 and Drupal, but at least in the mean time feels like this is a good place .. what do you guys think?

**Comment by merk** [comment]
I think if a library of code can be generated that can be used independently of symfony, and re-integrated using a bundle, it makes sense to move it out.

**Comment by stof** [comment]
agreed

**Comment by jmikola** [comment]
If other folks are on board with using it and it avoids someone creating a redundant library, let's do it :+1:

**Comment by stof** [comment]
@jmikola a use case is https://github.com/flintstones/Rest which currently requires using the bundle in the Silex project, which means lots of unneeded code specific to Symfony.

cc @igorw

**Comment by lsmith77** [comment]
ok .. i see this a go then. will create the repo as soon as i have some code.

**Comment by stof** [comment]
@lsmith77 you may want to create a repo by cloning FOSRestBundle and moving the classes in it. This would allow keeping the list of contributors and the history for the files (git is able to handle moved files in the history)
