### ISSUE TITLE
Add FOSAdvancedEncoderBundle

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/friendsofsymfony.github.io#25]
I just created https://github.com/stof/StofAdvancedEncoderBundle which allows to choose the encoder on an instance basis instead of just choosing it based on the class. It is inspired by what we have in FOSUserBundle currently but more flexible and available for any User implementation as it really don't need the UserManager for this.

@lsmith77 suggested to move the bundle to FOS in FriendsOfSymfony/FOSUserBundle#395 instead of having it under the `Stof` namespace.

**Comment by lsmith77** [comment]
+1 .. i am not 100% sure if it should be separate or not .. but leaning towards separate atm.

**Comment by stof** [comment]
@lsmith77 the reasoning is that this feature is totally different than the goal of FOSUserBundle (the user management). We can manage users without it, and we can use it with different user than the FOSUB ones if we separate things. So it is more flexible to split them in different bundles and people can then choose the feature they want. Implementing the interface in their entity extending the FOSUB model is not a big task as it is only one getter.

**Comment by lsmith77** [comment]
yes, that is why i am leaning towards having them separate. however the question is how many users will be confused by having two bundles and how many would be annoyed by having it all in one.

**Comment by stof** [comment]
Well, how many FOSUB user even _know_ that they can change the algorithm on an instance basis ?
This has never been documented so only people digging into the code can know about it, or people having an issue with our encoder stuff and asking for an explanation. Other ones will probably discover the feature when we will document that it has been moved and refactored in another bundle.

**Comment by willdurand** [comment]
Is this bundle a requirement for FOSUB or just an optional sep ?

**Comment by stof** [comment]
@willdurand a bundle independant from FOSUserBundle. They can be used together but none of them require the other one. Currently, FOSUserBundle contains a bad implementation of this feature (very intrusive and not flexible at all) and the goal is to separate it as it is totally independant from the other parts of FOSUserBundle..

**Comment by willdurand** [comment]
Yay, so a big +1

**Comment by arghav** [comment]
+1

**Comment by lsmith77** [comment]
so i think its a go :)

**Comment by stof** [comment]
well, I thought the requirement was half of the FOS guys ? We only have 4 votes and we are 13 in the organization

**Comment by stof** [comment]
@schmittjoh @jmikola @Herzult @kriswallsmith @everzet @avalanche123 @ornicar @tecbot @dstendardi ping

**Comment by lsmith77** [comment]
the reality is that most guys are simply not active enough to vote ..

**Comment by ornicar** [comment]
Indeed. You should remove me from the team. I think I can't do it myself.

I have a lot of fun with you guys! But I don't feel like a friend of symfony anymore.

**Comment by stof** [comment]
Moved to FOS. I will work on removing the code from FOSUserBundle this weekend
