### ISSUE TITLE
"assigning" maintainers

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#30]
so when we initially setup FOS we kind of expected for everyone to stick with their babies. the reality is of course that we had people join that have dropped off the face of the Symfony2 world ... some more some less .. and some just aren't following up on Bundles as their focus has moved on.

as a result i think it would be good to make sure we have 2 maintainers for each Bundle. if someone decides they are no longer interested, we can look for someone else to step up.

semi related (maybe a topic for another ticket):
we have several people that do not commit any code, nor do they react to tickets like this. overall i don't care if people are still members but don't do anything, but its makes it a bit hard to figure out if we have a majority. so maybe we should also mandate that people really need to show some activity or be removed. after all its easy to re-add people if they have time again.

**Comment by stof** [comment]
Assigning myself as a maintainer for the following repos:
- FOSUserBundle (eh, I think some people already figured it)
- FOSAdvancedEncoderBundle
- FOSJsRoutingBundle

I'm providing code reviews for all repos currently anyway.

**Comment by merk** [comment]
I think it is important to keep bundles maintained and identify those that are not being maintained.
- What should happen to bundles that have no maintainers? Do we archive them? Find someone who is willing to maintain them? (what if noone steps up?) Do we mark them as unmaintained?
- What level of activity should mark a bundle as unmaintained? Code committing? No responses to issues or PRs?

I wouldnt want to flag something as unmaintained/remove those maintainers if there is no work to be done on a bundle. Should we as a group get together to define a feature set to work towards for each bundle?

**Comment by willdurand** [comment]
I'm maintainer for FOSJsRoutingBundle and FOSOAuthServerBundle.
And, I review all Propel related PRs/issues (mainly in FOSUB).

I agree with @merk's qestions. We should define rules.

**Comment by jmikola** [comment]
I don't suppose [Still Maintained?](http://stillmaintained.com/) could help label bundle status? Seems like it's only for adding your own repositories and not for handling organizations.

Is there value to keeping folks around with repository access even if they are not maintainers? I assume being a maintainer for one or more bundles is the criteria by which a member would be considered active.

In the case of Doctrine, I'm not a maintainer; however, I've found that still having repository access has come in handy when I was able to fix a quick bug directly or merge an uncontroversial PR. I tend to think the same about FOS (at least for the bundles in use at OpenSky and Exercise).

**Comment by arghav** [comment]
I can maintain TwitterBundle.

I agree with @jmikola on the view about maintainers.

**Comment by lsmith77** [comment]
lets just write the names of the lead maintainers into the composer files ..

**Comment by lsmith77** [comment]
ping?

**Comment by jmikola** [comment]
Using `composer.json` sounds entirely reasonable.

**Comment by asm89** [comment]
Any more insights in this? Or is the only conclusion "maintainers add themselves to the composer.json file"?

**Comment by lsmith77** [comment]
yeah .. i think that is the conclusion.
