### ISSUE TITLE
Add asm89 to FOS

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/friendsofsymfony.github.io#31]
I'd like to propose adding @asm89 to the FOS team. He has been sending some great PRs to CB for a while now and has plans to evolve it into a disqus like solution, along with other integration with FOSRestBundle and other FOS bundles for authentication.

**Comment by stof** [comment]
first question to @asm89: what do you think about it ? Until now, the proposal has always been made by the guy himself

**Comment by asm89** [comment]
I'd like it. :) I've been collaborating quite a lot with @merk on the latest refactoring of FOSCB and it would be super to assist in maintaining the bundle and pushing it forward to a more complete and robust feature set.

**Comment by lsmith77** [comment]
+1

**Comment by arghav** [comment]
+1

**Comment by stof** [comment]
+1

**Comment by willdurand** [comment]
+1

**Comment by stof** [comment]
Closing as @asm89 has been added
