### ISSUE TITLE
Gathering at Symfony Live Paris

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/friendsofsymfony.github.io#32]
What do you guys think of getting together for a dinner one night during the conference?

**Comment by jmikola** [comment]
:+1: A few of us spontaneously went out last year during the first night of the conference IIRC. I ended up carrying leftover cheese in a big plastic bucket for most of the evening.

![](https://fbcdn-sphotos-a.akamaihd.net/hphotos-ak-snc6/188632_881194422375_22400656_47173762_7718216_n.jpg)

**Comment by lsmith77** [comment]
i am all in ..
will arrive in the 6th and depart on the 8th

**Comment by merk** [comment]
plan for me at this point is arrive some time on the 5th, staying till the 9th

**Comment by willdurand** [comment]
:+1: for me, but I don't know when I will arrive yet..

**Comment by stof** [comment]
:+1: for me

**Comment by jmikola** [comment]
The speaker dinner was moved to Thursday night (June 7). Does Wednesday, June 6 work for everyone? Alternatively, we could do Friday, am I'm sure there will be crowds going out for dinner, but that will be a much larger gathering :)

**Comment by stof** [comment]
@jmikola OK for me.

**Comment by lsmith77** [comment]
works for me

**Comment by merk** [comment]
Have fun guys, unfortunately circumstances didnt allow me to make it. Next time :)

**Comment by jmikola** [comment]
I'm suggesting the same restaurant as last year Wednesday at 8pm: https://twitter.com/jmikola/status/210140500362133504

We can spread out afterwards for drinks and such, but Le Zeyer should be able to accommodate a walk-in group for dinner again.

**Comment by asm89** [comment]
:+1: I arrive at Paris Nord at 1830. I'll follow some more FOS people on twitter. :)
