### ISSUE TITLE
Moving OrnicarMessageBundle to FOS namespace

### ISSUE THREAD

**Issue by jmikola** [FriendsOfSymfony/friendsofsymfony.github.io#33]
Pinging:
- @ornicar, who is the original author
- @khepin, who is volunteering to become the maintainer
- @cystbear, who is still using this at Exercise.com

Thibault and I are no longer working on [OrnicarMessageBundle](https://github.com/ornicar/OrnicarMessageBundle) and neither of us are able to properly review pull requests for this, much less continue development. If Thibault gives his blessing, I think moving this over to the FOS namespace will be in everyone's best interest.

I suppose we would do the same as was done for FOSUserBundle. Fork the original, give credit in the readme, and then rename and update the class and service namespaces throughout the project.

Cross-referencing: ornicar/OrnicarMessageBundle#59, which prompted this idea.

**Comment by stof** [comment]
@jmikola I would prefer avoiding having the FOS repo as a fork of the older repo. For FOSUserBundle, it confused people during several months to have the main repo not being the root on github. And contrary to the time FOSUserBundle was created from DoctrineUserBundle, it is now possible to move a repo to an organization without involving the github support.
So my recommended way would be to move it to FOS, clone it back on ornicar's account for BC for current users and then rename it in the FOS repo (and giving credit of course)

**Comment by willdurand** [comment]
I agree with @stof

2012/8/9 Christophe Coevoet notifications@github.com

**Comment by stof** [comment]
Btw, my vote is +1 if they continue maintaining it (not like the move of FOSFacebookBundle for instance). But I don't want to add more unmaintained repos to FOS.

**Comment by jmikola** [comment]
Ah, I wasn't aware that GitHub would relocate repositories like that. That makes sense. It's up to Ornicar if he wants to clone it back, of course :)

If @khepin is going to be the only maintainer, it might be preferable for him to just fork it to his own namespace. My goal was just to get the conversation started, so I'll wait for him to chime in.

**Comment by khepin** [comment]
Either solutions could be fine for me if I'm now "the only person" using this.

I'm not sure what being under the FOS namespace would mean and involve exactly. If it means it'll be easier for me to ask questions and tap into the knowledge and experience of the current FOS members regarding the maintenance of this bundle, then it sure seems an interesting option to me.

**Comment by cystbear** [comment]
@jmikola I do not mind any consistent changes

**Comment by gimler** [comment]
+1

**Comment by ornicar** [comment]
:+1: for getting rid of it :)
Before you take it under your protection, you may want to take a look at the code. It is convoluted and overengineered if I remember correctly.

**Comment by gimler** [comment]
i think the spam protection can be moved into a seperate bundle.

The search stuff should be removed it is not the focus off the bundle this can be done by for example FOQElasticaBundle

The directory structure should be cleaned e.g. move the form type model ... into Form dir...

**Comment by khepin** [comment]
@ornicar I took many one looks at the code! It is indeed a little bit overengineered but it's not that bad and after going through it a few times it's ok.
@gimler I agree that search doesn't really seem to belong here directly. And spam detection probably should be a default implementation that is easy to replace / customize. Haven't looked at it so much.

**Comment by cystbear** [comment]
Thi, I think one day you will back to awesome PHP world :) @ornicar

**Comment by ornicar** [comment]
just ping me if you agree on doing it, and I'll move the repo.

@cystbear Maybe in another life :)

**Comment by zocimek** [comment]
So what's the plan? I'd like to know because I'm going to maintain this bundle too and use it in some projects. I don't know if i have to wait for moving bundle to FOS namespace or use my own fork

**Comment by ornicar** [comment]
As  I said, I'm all for it. Just waiting for FOS team approval.

**Comment by jmikola** [comment]
@stof: Based on the above, it seems both @zocimek and @khepin would like to actively maintain the bundle. I'm not sure we'd be able to get a majority of the [FOS members](https://github.com/FriendsOfSymfony) to vote on this, though.

**Comment by khepin** [comment]
Not sure how the FOS organization works internally but how about we decide on a timeframe for this. And then either move the bundle to FOS or somewhere else where @zocimek and I can start maintaining the bundle.

If the bundle is moved to somewhere else than FOS, then who would be the collaborators to add?

@jmikola 
@zocimek 
@cystbear 
@stof 

Any others?

What could be a good timeframe to give enough time for FOS to reach a decision but also not wait months before we can start work on the bundle?

**Comment by stof** [comment]
ping @FriendsOfSymfony/owners please vote on this

**Comment by merk** [comment]
:+1:

**Comment by willdurand** [comment]
:+1:

**Comment by merk** [comment]
I'm putting my hat in for helping out where I can with this bundle: I have every intention of using it, when I find some time for my side projects.

**Comment by asm89** [comment]
Two questions:
- This would also add 3 members to FOS? :) Or only @khepin as bundle maintainer? (That's what the start post mentions.)
- @jmikola is mentioned as 'collaborator' if the bundle would move somewhere else. Does this mean you'll be helping on the maintenance of the bundle when it's moved to FOS? The start post talks about you not helping on the maintenance anymore.

Is essence I'm :+1:, it's just that I lost what we're exactly voting for.

**Comment by schmittjoh** [comment]
Same here, +1 for the bundle, -1 for adding 3 maintainers for it.

**Comment by ornicar** [comment]
I cannot move it to FOS without FOS admin credentials. Give them temporarily to me if you want me to perform the transfer.

**Comment by stof** [comment]
@ornicar done

**Comment by ornicar** [comment]
Done: https://github.com/FriendsOfSymfony/OrnicarMessageBundle

You can remove my credentials.
You may also want to rename the bundle to FOSMessageBundle or anything, I agree by advance.

Thanks for hosting the bundle!

**Comment by stof** [comment]
@ornicar I suggest you to fork it on your account (before any remaining) to provide some BC for people using it already

**Comment by stof** [comment]
and you're not a FOS guy anymore again :)

**Comment by ornicar** [comment]
Yep good idea, I forked it and added some redirect.

**Comment by schmittjoh** [comment]
I think I confused it with the GravatarBundle, just got a shock when I
looked at the root. Please reduce the number of folders! :)

**Comment by jmikola** [comment]
@asm89: I'm no longer work on Exercise.com's application, so I will not be maintaining this. That was the reason for suggesting it move out of Thibault's domain, since he and I were the only folks with write access. I can't speak for @cystbear and @AlexKovalevych, but I believe the bundle presently works fine for Exercise.com's needs. Other folks obviously seem to need more functionality :)

I just created a "FOSMessageBundle" team (push/pull/admin roles), added @khepin and @zocimek, and assigned it to the "OrnicarMessageBundle" repository. The next step will be renaming the repository and altering all namespace references throughout the code. I created an issue for that on the project, but I think we're done here. I'll let someone else close this out.

**Comment by ornicar** [comment]
Good job guys, thank you!

**Comment by zocimek** [comment]
Repository has been renamed to FOSMessageBundle currently only on branch master
@ornicar if you could updated refs in doc to https://github.com/FriendsOfSymfony/FOSMessageBundle

all changes are in https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/71

**Comment by ornicar** [comment]
Yep, done

**Comment by zocimek** [comment]
I think this issue is done please verify and close ;]
