### ISSUE TITLE
New maintainer for FOSFacebookBundle

### ISSUE THREAD

**Issue by diegoholiveira** [FriendsOfSymfony/friendsofsymfony.github.io#34]
There is a lot of PR waiting for revision on the bundle repository, and since I'm using this bundle a lot in a project, I can be the maintainer for this bundle (it's just a suggestion, can be someone else).

For me it's important keep this bundle updated.

How can we proceed to choose someone to be in charge of this bundle?

**Comment by lsmith77** [comment]
Right now we do not have any member of FOS looking after the facebook and twitter bundles. especially the facebook one has PRs piling up and @diegoholiveira seems to be one of the most active people. so i am +1 to give him access to at least the facebook bundle.

**Comment by arghav** [comment]
:+1:

**Comment by asm89** [comment]
Since the bundle is brought up here, maybe we should consider deprecating/removing the login functionality of the bundle? I see a lot of questions coming by on for example IRC of people using the bundle solely to login on facebook. Those people are probably better of using HWIOAuthBundle.

**Comment by merk** [comment]
I am +1 for anything that will end up increasing activity of the FOS bundles and reduce the support questions occuring in #symfony.

Are you willing to increase the documentation quality as well as maintain the code, @diegoholiveira?

**Comment by lsmith77** [comment]
@asm89 yeah .. makes sense to me as well.

**Comment by diegoholiveira** [comment]
@merk: about improve the docs, sure that I'll work on it.

@asm89, @lsmith77: FOSFacebookBundle are just about Login. If we deprecate the login functionality, it's better deprecate all bundle, no?
I take a look on HWIOAuthBundle and it seems to be an excellent choice to provide login functionality on Facebook and another services.

## 

Diego Oliveira
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by arghav** [comment]
This case applies to TwitterBundle too. Since the main use of both these bundles is to integrate with Symfony security it might not make sense to maintain these two anymore. For using the specific API it's just a matter of creating a service.

**Comment by schmittjoh** [comment]
The last time I checked HwiOauthBundle was not so extensible because it
provides integration for a lot of different providers.

Personally, I'm still using the TwitterBundle.

**Comment by asm89** [comment]
The bundle indeed focusses on providing oauth1/2 login integration and provides a lot of different providers that are pre configured.

**Comment by diegoholiveira** [comment]
Like @schmittjoh, I'll keep using FOSFacebookBundle. But I guess we need to decide if we'll keep it or not. And if we decide to keep, I can be in charge of it.

**Comment by stof** [comment]
@diegoholiveira FOSTwitterBundle is providing more stuff than just the OAuth login.

**Comment by lsmith77** [comment]
i think its clear that there is interest in the Bundle .. even just "legacy" interest. same applies to FOSTwitterBundle. so imho we should just add @diegoholiveira as he is willing to step up.

**Comment by lsmith77** [comment]
so atm we have a +1 from @merk, @kertz ... anyone else?

**Comment by jmikola** [comment]
:+1:

**Comment by khepin** [comment]
:+1:

**Comment by asm89** [comment]
:+1: I still hope we can figure something out on the authentication part though. Quite some users seem to want login with social providers, not only facebook. I still see a lot of questions coming by about this on IRC. HWIOAuthBundle is not perfect yet, but I've been working hard with @stloyd to make using the bundle for authentication as effortless as possible, as extra it already provides FOSUserBundle integration out of the box.

@diegoholiveira Let me know what you think. :)

**Comment by diegoholiveira** [comment]
@asm89 I do agree in deprecate this bundle in favor of HWIOAuthBundle.

I'll keep to using FOSFacebookBundle because it's already working on my project and I can't migrate to HWIOAuthBundle now.

If we decide to deprecate it, we still need to choose a new maintainer of the bundle?

Notice: I'm not saying that we need to deprecate FOSFacebookBundle, but if we do it, I'll not be against it.

**Comment by schmittjoh** [comment]
+1

**Comment by lsmith77** [comment]
ok .. we are still not at half of the current members .. but i decided to just do ahead an add @diegoholiveira into the FOS Owner group in this repo as well as the FOSFacebookBundle team in the respective repo.

**Comment by diegoholiveira** [comment]
Thanks @lsmith77, I'll do my best on FOSFacebookBundle :)

**Comment by stof** [comment]
@lsmith77 the repo teams are useless since the refactoring of the github notification system. Previously, orga owners were not notified without being in a team with write access, so we created these teams. Now, you choose on a per repo basis (and it is activated by default when you have write access, which includes owners)
