### ISSUE TITLE
propose import BazingaOAuthServerBundle as a bundle for Oauth1.0a support

### ISSUE THREAD

**Issue by cordoval** [FriendsOfSymfony/friendsofsymfony.github.io#35]
propose
- import BazingaOAuthServerBundle --> FOSOAuth1ServerBundle  as a bundle for Oauth1.0a support
- rename FOSOAuthServerBundle ---> FOSOAuth2ServerBundle
- I will maintain it as I am using it in production

**Comment by stof** [comment]
I'm -1 on renaming the FOSOAuthServerBundle (which would be a BC break).

And is it worth it moving the Bazinga bundle (which would also be a BC break for people using it) ? @willdurand thoughts ?

**Comment by cordoval** [comment]
@stof you are assuming too much that 1.0 is not in use, where the case is actually the opposite, 1.0 is considered by many even better than 2.0 in some cases, (merk thinks this way on IRC). So BC is some concern but not like we cannot move forward improving the bundle if we rename it then there is no BC so not sure why you still think it is a bad idea.

**Comment by willdurand** [comment]
-1 on renaming the existing FOSOAuthServerBundle.

No problem to rename the BazingaOAuthServerBundle to whatever OAuth1ServerBundle. I don't know anyone who is using it at the moment, never got bug fixes or issues;

+0 on moving it to the FOS organisation. At first glance, it would be nice as it will get more attention from the community, but there are already more bundles than active maintainers so.. I don't know, I would prefer to make the bundle strong before to move it.

**Comment by cordoval** [comment]
great so let's see how evolves and we can move it to FOSOAuth1

**Comment by stof** [comment]
Closing this as there seem to be no real interest into moving it, and we are already short of maintainers. The bundle can be perfectly used from its current location.
