### ISSUE TITLE
Moving FOQElasticaBundle to FOS namespace

### ISSUE THREAD

**Issue by jmikola** [FriendsOfSymfony/friendsofsymfony.github.io#37]
The reasons for this are similar to my previous proposal to move OrnicarMessageBundle (#33). Exercise.com is using this bundle (likely an older version), but they no longer actively develop it. I picked up development of it at Exercise after @ornicar departed, and then @richardmiller came aboard last year, as I believe he was using it for a client project at Sensio. Since then, we've both been stretched thin and haven't given it the attention it needs, as the pile of issues and PRs will attest..

At Liip, @leahaense has been given a budget to work on the bundle (in conjunction with some projects), and I spoke to @dbu about Liip becoming involved in it the Sunshine PHP conference. I also spoke to @jseverson, Exercise's CTO, and he is in favor of moving it.

Having learned from OrnicarMessageBundle's migration, I would propose using Github's tool to transfer to repository to FOS, and then immediately fork it back to Exercise (and update the readme file). The original composer package could be left as-is, but we'd rename the namespace/bundle from FOQ to FOS and then create a new package under the FOS vendor on packagist.

Initial maintainers of the bundle would be myself, @richardmiller, and @leahaense (and perhaps @dbu).

**Comment by ornicar** [comment]
It's just a letter to change.

**Comment by merk** [comment]
I'm using this bundle and would assist in maintenance.

:+1:

**Comment by dbu** [comment]
i agree with the plan. and would be happy to have maintainer rights just in case, though i don't plan to actively work on this atm.

**Comment by arghav** [comment]
:+1:

**Comment by willdurand** [comment]
:+1:

**Comment by asm89** [comment]
In principle I'm :+1: for moving the bundle, but -1 for adding 3 maintainers for it. Only thing I'm wondering about is how much the move is worth? Aren't the same people already maintaining the bundle?

**Comment by jmikola** [comment]
@asm89: Since none of us work for Exercise.com (I technically shouldn't still have access to it :), the goal is to get it into a more common namespace.

**Comment by jmikola** [comment]
So far, 5 of 17 positive votes: @khepin, @jmikola, @merk, @willdurand, and @asm89 (if my above response is agreeable with him)

Four more would constitute a majority: @arnaud-lb, @avalanche123, @diegoholiveira, @dstendardi, @everzet,
@Herzult, @kriswallsmith, @lsmith77, @schmittjoh, @stof, @tecbot, @zocimek

I'm going to apply the bundle versioning today (see: Exercise/FOQElasticaBundle#242), and would hopefully like to move this over and create the new Packagist packages soon after.

**Comment by jmikola** [comment]
Since GitHub seems to limit user-tagging (probably for good reason): @Herzult, @kriswallsmith, @lsmith77, @schmittjoh, @stof, @tecbot, @zocimek

**Comment by lsmith77** [comment]
+1 which i guess would also mean we would add the maintainers to FOS

**Comment by schmittjoh** [comment]
+1

On Thu, Mar 7, 2013 at 10:40 PM, Lukas Kahwe Smith <notifications@github.com

**Comment by kriswallsmith** [comment]
:+1:

**Comment by jmikola** [comment]
@lsmith77: @merk and I are already on board, so I suppose @richardmiller and @leahaense would be the new faces. Optionally, @dbu.

It might be a good idea to come up with a document that tracks who is actively working on specific bundles. I think keeping that in this repository might be better than in the individual bundle README files. Thoughts?

**Comment by lsmith77** [comment]
well our entire "governance" concept has kind of failed to meet reality. originally the idea was to collaborate together on the bundles. the reality is that FOS has become a bit of a quality brand but each bundle is maintained by an almost disjunct set of members.

**Comment by stof** [comment]
@jmikola We agreed a while ago about doing it by adding them as author in the composer.json

**Comment by jmikola** [comment]
@stof: Thanks. That makes sense.

**Comment by dbu** [comment]
i think it makes sense to not add me as maintainer to fos at this moment. we can still do that when i take active ownership on one of the bundles.

**Comment by asm89** [comment]
@jmikola :+1: thanks for your response, happy to see the move. :)

**Comment by dbu** [comment]
so when is the repository moved? there are some open pull requests over at Exercise, not sure if they would be moved along by github or get lost.

**Comment by jmikola** [comment]
Just moved things over to https://github.com/FriendsOfSymfony/FOSElasticaBundle, and will now proceed with other tasks in FriendsOfSymfony/FOSElasticaBundle#242.

https://github.com/Exercise/FOQElasticaBundle will remain in place, with links pointing to the FOS bundle. More importantly, git submodules and it's composer package will still be accessible.

**Comment by jmikola** [comment]
@dbu: I didn't add you as a maintainer (just @leahaense), but feel free to ping me if you'd like access. Otherwise, it's currently Richard, Oleg, and myself.

**Comment by dbu** [comment]
thanks a lot for the work jeremy. that is fine, i don't need commit
access at this point. i will contact you if things change.
i wonder if there is something we can do to to make packagist prefer the
FOS repo, and show a prominent warning to people trying to use the old repo.

**Comment by merk** [comment]
Trigger a deprecation warning in the bundle's init() method in the FOQ bundle telling people to use FOSElasticaBundle instead.

**Comment by stof** [comment]
@merk Not in init (which does not exist) and not in `boot` either (which is called before the logger is added in the error handler and so would not be collected in the profiler). It should be done somewhere being called only later so that it appears in the WDT.

**Comment by jmikola** [comment]
I'll defer to you guys for the best way to handle that. I've disabled issues on the Exercise repository, but pull requests are still open :)

Since FOSElasticaBundle includes a namespace change, I didn't want to mess with the original package. Folks that would rather not update their code can still use FOQ. I'm sure word will get out about the migration soon enough -- all of the watchers on GitHub are not pointing to the FOS repository.
