### ISSUE TITLE
Adding PHPUnit as a dev requirement

### ISSUE THREAD

**Issue by jmikola** [FriendsOfSymfony/friendsofsymfony.github.io#39]
This came up in FriendsOfSymfony/FOSElasticaBundle#283, and the argument was that not everyone is using PEAR to install global deps anymore, so this eases development and testing for some. I'm curious what everyone thinks about this. I don't believe Symfony and other FOS bundles are doing this, but I've seen it in some libraries before.

**Comment by diegoholiveira** [comment]
We have already used on FOSFacebookBundle.
I do recommend to everyone close to me, to use only composer to install
everything, included phpunit and another QA tools.

**Comment by stof** [comment]
The reason why this has been rejected in Symfony is that it would make the install longer (installing PhpUnit and all its dependencies) on systems where phpunit is already available, for instance Travis.

**Comment by lsmith77** [comment]
i would vote against it for the same reason.

**Comment by merk** [comment]
phpunit.phar is available for those who are unable to configure PEAR to get it.

:-1:

**Comment by willdurand** [comment]
I'm :-1: for the same reasons above.

**Comment by diegoholiveira** [comment]
I don't get it. You guys reject it because travis? or the same argument for long installs can fit on others environments?

**Comment by lsmith77** [comment]
not just travis .. i also do not want to have to download phpunit when i run the tests locally.

**Comment by jmikola** [comment]
Ah, I didn't realize PHPUnit was also available as a PHAR package.

Thanks for all the quick responses. I think there's a general consensus here, so I'm going to close this out.
