### ISSUE TITLE
Create a gitter room

### ISSUE THREAD

**Issue by AlmogBaku** [FriendsOfSymfony/friendsofsymfony.github.io#52]
https://gitter.im/

It just an awesome way to communicate with OS projects :) lets open a room about FOS projects

**Comment by willdurand** [comment]
There is already an IRC channel..

**Comment by AlmogBaku** [comment]
@willdurand yeah, but from my experience with mean.io, it's just a great tool(and it encouraged me to contribute more).
The thing is IRC is kinda dead.. and gitter and its replacements allows you to talk on realtime about the repo without any need of weird and annoying bots.

give it a try :)
