### ISSUE TITLE
FOSCommentBundle maintainer

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/friendsofsymfony.github.io#53]
I've been approached by @XWB who would like to take over maintainership of FOSCommentBundle.

He has contributed to the bundle already (https://github.com/FriendsOfSymfony/FOSCommentBundle/commits?author=XWB).

I am :+1: for this.

**Comment by lsmith77** [comment]
+1

**Comment by lsmith77** [comment]
cc @owners

**Comment by asm89** [comment]
:+1: 

@XWB is my former colleague at Hardware.Info. Most of my contributions to this bundle are from the time I worked there as well.

**Comment by stof** [comment]
@lsmith77 the way to notify owners is @FriendsOfSymfony/owners . You notified a different organization here

**Comment by stof** [comment]
:+1:

**Comment by merk** [comment]
I have added @XWB to the FOS organisation. Welcome aboard!
