### ISSUE TITLE
add some more people with commit rights to FOSRestBundle

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#55]
I would like to give some more people commit access to FOSRestBundle both to recognize their contributions but also to make contributions easier and maybe also entice more contributions ;)

Specifically I want to give @xabbuh and @Ener-Getick access ..

**Comment by lsmith77** [comment]
ping @FriendsOfSymfony/founders

**Comment by merk** [comment]
:+1:

**Comment by dbu** [comment]
:+1:

**Comment by lsmith77** [comment]
done
