### ISSUE TITLE
FOSOAuthServerBundle maintenance

### ISSUE THREAD

**Issue by GuilhemN** [FriendsOfSymfony/friendsofsymfony.github.io#56]
There are many PRs / issues opened in [FOSOAuthServerBundle](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pulls)... 
Is this bundle still maintained ?

If you agree, I'd like to be a collaborator of this bundle to help cleaning this a bit (I'm already a collaborator of the `FOSRestBundle`).

ping @FriendsOfSymfony/fosoauthserverbundle

**Comment by GuilhemN** [comment]
ping @FriendsOfSymfony/founders

**Comment by willdurand** [comment]
AFAIK @alanbem was the only active maintainer.

**Comment by GuilhemN** [comment]
Arf I would like to use this bundle in a symfony 3 project but it is not compatible yet...

**Comment by merk** [comment]
Is there any reason you cant give the alternative bundle/library that will eventually replace FOSOAuthServerBundle?

https://github.com/Spomky-Labs/oauth2-server-library
https://github.com/Spomky-Labs/OAuth2ServerBundle

I cant speak to their readiness for use (and there might be lacking documentation) but there is activity in this repositories and it looks like theres quite a bit more test coverage.

**Comment by GuilhemN** [comment]
This would mean abandoning completely FOSOAuthServerBundle... 
Would be great to have feedbacks from someone who tried several oauth bundles to take a decision.

**Comment by merk** [comment]
I plan on changing our server implementation to SpomkyLabs's bundle/library next major version.

**Comment by willdurand** [comment]
@Ener-Getick are you a maintainer of FOSOAuthServerBundle yet? If not, I'd like to promote you.

**Comment by GuilhemN** [comment]
@willdurand no, I'm not. I would be glad to help maintain this bundle :-)

**Comment by willdurand** [comment]
cool. you're now a maintainer for this bundle! Congratz!

**Comment by GuilhemN** [comment]
thanks :smile:

**Comment by nicosomb** [comment]
\o/ @Ener-Getick we are now waiting for you to release new versions ;-)

**Comment by GuilhemN** [comment]
@nicosomb yeah I'm just looking what is waiting to be released to be sure it is ready ;-)

**Comment by j0k3r** [comment]
Great! What about https://github.com/FriendsOfSymfony/oauth2-php ?

**Comment by GuilhemN** [comment]
@j0k3r see https://github.com/FriendsOfSymfony/oauth2-php/releases/tag/1.2.0

**Comment by j0k3r** [comment]
@Ener-Getick wow didn't notice that, awesome

**Comment by GuilhemN** [comment]
@j0k3r I just released it, there is an issue on the github interface ^^
