### ISSUE TITLE
Create Symfony HTTP Cache repository.

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/friendsofsymfony.github.io#57]
Hi

We have been discussing (at [FOSHttpCache](https://github.com/FriendsOfSymfony/FOSHttpCache/issues/286#issuecomment-207383077)) the creation of a repository dedicated to extending the [Symfony HTTP cache](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/HttpKernel/HttpCache).

Currently the FOSHttpCache can add the following features to the Symfony HttpCache:
- An event dispatching trait for the HTTP cache.
- Setting a Custom TTL
- Adding Debug headers
- Purge support
- User context support

We now want to also add tag invalidation capabilities and it occurs to us that this is outside of the scope of the FOSHttpCache (which provides an abstraction to third-party cache servers) and also that all of these features can be used without the infrastructure of the FOSHttpCache component.

So I would like to propose the creation of a `FOSSymfonyHttpCache` repository (or alternatively `FOSHttpKernelCache`, or anything suitable).

**Comment by dbu** [comment]
:+1: 

as maintainer of FOSHttpCache i support this idea. we are preparing for a version 2 of FOSHttpCache, this would be a good oportunity to split out this part of the package which is becoming too large and dilluting the focus of the FOSHttpCache library.

**Comment by dantleech** [comment]
ping

**Comment by GuilhemN** [comment]
👍 I think we should split our repositories more often when they become too large.

**Comment by stof** [comment]
:+1: for splitting the library to keep the scope maintainable

**Comment by dbu** [comment]
i heard no doubts or downvotes. it seems i have the rights to create that repository. ok if i create `FOSSymfonyHttpCache` now? @dantleech are you still up to lead this effort?

**Comment by dantleech** [comment]
Do we still want to do it; I was under the impression that Symfony 3.0
will support tag invalidation natively?

**Comment by dbu** [comment]
that was a confusion i created. symfony added a caching component that
among other things supports tagging. HttpCache does not use that
component yet. but indeed, maybe we better try to contribute to symfony
itself to make HttpCache use the caching component to get tag
invalidation support into it.

**Comment by dbu** [comment]
@dantleech i am trying to wrap up FOSHttpCache 2.0 - what about the topic of splitting out the symfony HTTP cache implementation into its own repository? do you want to do it? if you don't i guess i will keep it in FOSHttpCache for 2.0 and we can see about removing it in 3.0

**Comment by dantleech** [comment]
I suppose the least we could do is spiit it out without modifying the code, create/move the documentation and tag it as 1.0, not sure if I have time to add the tag functionality or otherwise work much on the code at this point.

**Comment by dbu** [comment]
that sounds like a plan. should we move both the reverse proxy and the
proxy client? they do not directly depend on each other, but its likely
easier to functional test when they are together. moving the client makes
the coupling from the new repo to the FOSHttpCache rather strong, but imo
thats ok and the base client needs to strictly keep BC anyways

**Comment by dbu** [comment]
FOSHttpCache contains the symfony reverse proxy extensions, and for tag support there is toflar/psr6-symfony-http-cache-store
