### ISSUE TITLE
adopting IvoryCKEditorBundle

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/friendsofsymfony.github.io#58]
There is a group of people who want to take over maintenance of https://github.com/egeloen/IvoryCKEditorBundle

Its a popular Bundle that is therefore also featured in the Symfony docs
https://symfony.com/doc/master/bundles/IvoryCKEditorBundle/installation.html

The three people that want to maintain the Bundle are:
@kunicmarko20, @fbourigault, @electricmaxxx

They would like to bring it under the umbrella of FOS to have a more agnostic organization/namespace for this effort.

**Comment by lsmith77** [comment]
@FriendsOfSymfony/founders please let me know if you are ok with this

**Comment by kunicmarko20** [comment]
One more thing, as we can't reach @egeloen we would need to fork the repository.

**Comment by dbu** [comment]
i don't know if i am allowed to vote, but with a group of 3 maintainers that sounds pretty solid to me, so i am :+1:

**Comment by kunicmarko20** [comment]
~As this is going nowhere, I don't want to be part of it. Do what you want. Thank you for your time.~ (Think before you post something like this again.)

**Comment by lsmith77** [comment]
sorry. I dropped the ball on this one. In my defense I am this month mostly not on my computer since I am taking care of my daughter full time. 

since there was no opposition I guess we can do this.

now do you prefer to fork or should I create a new repo. since @egeleon cannot be reached I think the appropriate thing is infact to change the namespace in which case I propose to create a new repo and assign admin rights to the 3 maintainers

**Comment by GuilhemN** [comment]
:+1: for creating a new repo. Moreover when seing github's fork link I always wonder if the repo is a WIP/for a PR...

**Comment by lsmith77** [comment]
ok creating FOSCKEditorBundle

**Comment by lsmith77** [comment]
done https://github.com/FriendsOfSymfony/FOSCKEditorBundle

again sorry for the delay

**Comment by ElectricMaxxx** [comment]
@lsmith77 we should not forget `egeloen/json-builder` as it is tightly coupled into the CkEditorBundle or at least we should discuss how to handle that dependency which also holds symfony dependencies.

**Comment by kunicmarko20** [comment]
@lsmith77 I read that on twitter (about daughter), I am sorry I forgot. I overreacted and handled this very badly I should have reconsidered my comment before posting it, this is still FOSS. Thank you for everything you do.

@ElectricMaxxx it is one line, and since we are not forking it, but moving it + namespace change, we can probably drop that dependency.

**Comment by lsmith77** [comment]
just let me know if you need another repo. but yeah for a few or even one line, probably not worth it. 

@kunicmarko20 thx for the apology. thank you for working on this Bundle :)
