### ISSUE TITLE
ABTestingBundle

### ISSUE THREAD

**Issue by naholyr** [FriendsOfSymfony/friendsofsymfony.github.io#8]
Hello,

I'd like to provide an AB Testing helping bundle. The aim of this bundle is to help developer to implement A/B testing with no pain :
- Declare "AB test suites" in configuration file or as a class (not decided yet, but I like the class idea, more versatile, and you'd just have to enable/disable a AB testing class in your configuration) :
  - name/description
  - number and names of "contexts" ("A" & "B" will be default, but you could use "Red" & "Blue" & "Green").
- For each context you'll tell that :
  - you replace a template by another, replace a class by another, etc... So that a context "A" can present a totally different feature than "B" to the visitor.
  - optionnaly (not in initial release of bundle), you may want a specific frequency, or that this context depends on another testing context (for example, if the test suite "MyFirstTest" is in context "A", maybe your test suite "MySecondTest" MUST be in context "A" too, you should be able to configure that).
- Each visitor will be assigned a context for each active test suite at the start of his session, and not change during its session.
- Each test suite has a number of metrics, used to determine which one won.
  - Attributing points to a test's metric could be done with something like a call to `$this->container->get('fos_ab.metrics')->save('MyTestSuite', array('metric' => +1))`.
  - The bundle must provide a user-friendly interface to list active test suites (why not enabling/disabling here in the UI ?), and consult the metrics.
- of course user-agnostic and persistency-agnostic, but with default use of UserBundle and Doctrine ORM to provide "out of the box" usable plugin.

I've not started working on this component, I'll start this week and may push first prototype next week-end. I'll push to my own repo, or directly here depending on your decision and when you give your response ^^

Thanks !

**Comment by ornicar** [comment]
Dude this looks complex. I'm not expert of A/B testing, but I guess it would be nice to have it in the FOS\ namespace.

Just a note about "out of the box" usable plugin: it's great as far as it does not limit **extensibility**.
For example in UserBundle, you must create your own user class before using the bundle.

**Comment by naholyr** [comment]
As this must be persistence and session agnostic, I suppose this should be achieved providing an interface and letting end user implement. But I like the idea of providing a "default" implementation too (based on Doctrine & UserBundle).

My general opinion is: provide high configurability, with intelligent default values. This is what I mean with "out of the box" ;)

**Comment by ornicar** [comment]
This is not always possible. Doctrine 2.0 does not let us extend the mapping of a non mapped-superclass.

This means you cannot provide a usable concrete entity, and let us extend it at the same time.
In UserBundle we chose to provide an abstract User entity so developers are forced to extend it.

**Comment by naholyr** [comment]
OK I may not realize yet all the implementation specifics as it's just being specified for now. That's not the main point anyway, a copy-paste from doc (like in UserBundle) worth a default implementation ^^

**Comment by lsmith77** [comment]
I think the heavy lifting for the charting should be in a separate bundle. To me the main task of this bundle would be managing information in the session (and cookie even) about what user is put into which test group and providing a logging mechanisms.

The data in the session might provide a standardized data structure to make stuff like dynamically setting the parameters easier. Actually maybe some sort of "wrapper" services (templating, forms etc) so that the change in behavior can mostly be injected into Controllers without modification would be cool.

**Comment by lsmith77** [comment]
BTW: for controllers that inject the service container I might suggested looking into https://github.com/lsmith77/Symfony2-Container-service-wrapper to make it possible to inject different services than the hardcoded ones.

**Comment by lsmith77** [comment]
BTW: As for contributing. I suggest you start off in your own workspace. For one since we do not know each other its hard to see if your style and vision matches those of FOS. Then when there is more to see we can decide if to include it in FOS or whatever. Though I am sure several of us will follow your development closely regardless where the code lives in github :)

**Comment by naholyr** [comment]
I like your idea of separating tasks lsmith77, I may go in this direction yep, providing separate bundles & services.

No problem to start on my side, see you in a few days ;)
